# Minimal test configuration for live trading validation
# USE WITH EXTREME CAUTION - REAL MONEY TRADING

# Environment
env: 'prod'

# RPC and API endpoints
rpc_url: '<YOUR_HELIUS_OR_HIGH_QUALITY_RPC>' # Use Helius or other high-quality RPC
helius_api_key: null # REQUIRED: Set via environment variable HELIUS_API_KEY
birdeye_api_key: null # REQUIRED: Set via environment variable BIRDEYE_API_KEY
dexscreener_base: 'https://api.dexscreener.com/latest/dex'
jupiter_base: 'https://quote-api.jup.ag/v6'
gmgn_base: null # Optional GMGN API for additional data

# Transaction settings (minimal for testing)
priority_fee_microlamports: 10000 # Conservative priority fee
compute_unit_limit: 120000 # Standard compute unit limit
jito_tip_lamports: 0 # No Jito tip for testing
tip_account_b58: null # Jito tip account in base58 format
max_slippage_bps: 50 # 0.5% max slippage (very conservative)

# Risk management (minimal amounts for testing)
position_size_usd: 1.0 # Minimal amount for testing
daily_max_loss_usd: 5.0 # Very conservative daily loss limit
cooldown_seconds: 120 # 2 minutes between trades (longer for testing)

# Notifications (REQUIRED for testing)
telegram_bot_token: '<token>' # REQUIRED: Set your Telegram bot token
telegram_admin_ids: [123456789] # REQUIRED: Add admin Telegram user IDs

# Data storage
database_url: 'sqlite+aiosqlite:///./minimal_test.sqlite' # Separate database for testing
parquet_dir: './minimal_test_data_parquet'

# Execution mode
dry_run: false # Live trading for minimal test

# Live trading configuration
preflight_simulate: true # Enable preflight simulation for live trades
max_retries_send: 3 # Maximum retries for transaction sending

# Signer configuration (choose one method)
keypair_path_enc: './secrets/solana-main.enc' # decrypted in-memory via secret_vault
keypair_path_json: null # alternative JSON keypair path
external_signer_cmd: null # alternative signer command

# Safety settings (strict for testing)
allow_devnet: false # Never allow devnet in production
unsafe_allow_high_slippage: false # Never allow high slippage in production
