# Paper trading configuration
# Used for strategy testing with simulated trades

# Environment
env: "paper"

# RPC and API endpoints
rpc_url: "https://mainnet.helius-rpc.com/?api-key=dd3e31d8-fbf3-465c-9dd1-ce8d2a4edd70"
# Jupiter API doesn't require API key - used for all data fetching
jupiter_base: "https://quote-api.jup.ag/v6"
gmgn_base: null  # Optional GMGN API for additional data

# Transaction settings (realistic for paper trading)
priority_fee_microlamports: 5000  # 0.005 SOL priority fee
compute_unit_limit: 140000  # Standard compute unit limit
jito_tip_lamports: 10000  # 0.01 SOL Jito tip
max_slippage_bps: 150  # 1.5% max slippage

# Risk management (moderate for paper trading)
position_size_usd: 100.0  # Medium position size for testing
daily_max_loss_usd: 200.0  # Moderate daily loss limit
cooldown_seconds: 60  # 1 minute between trades

# Notifications (recommended for paper trading)
telegram_bot_token: null  # Set via environment variable TELEGRAM_BOT_TOKEN
telegram_admin_ids: []  # Add your Telegram user ID for notifications

# Data storage
database_url: "sqlite+aiosqlite:///./paper_bot.sqlite"
parquet_dir: "./paper_data_parquet"

# Execution mode
dry_run: true  # Always dry run in paper mode
