# Production configuration
# Used for live trading - USE WITH EXTREME CAUTION

# Environment
env: 'prod'

# RPC and API endpoints
rpc_url: 'https://mainnet.helius-rpc.com/?api-key=dd3e31d8-fbf3-465c-9dd1-ce8d2a4edd70'
helius_api_key: 'dd3e31d8-fbf3-465c-9dd1-ce8d2a4edd70'
jupiter_base: 'https://quote-api.jup.ag/v6'
gmgn_base: null # Optional GMGN API for additional data

# Transaction settings (optimized for production)
priority_fee_microlamports: 20000 # example - adjust based on network conditions
compute_unit_limit: 120000 # Standard compute unit limit
jito_tip_lamports: 0 # keep 0 to omit unless you know what you're doing
tip_account_b58: null # Jito tip account in base58 format
max_slippage_bps: 100 # 1% max slippage (conservative)

# Risk management (conservative for production)
position_size_usd: 50 # Start small and increase gradually
daily_max_loss_usd: 200 # Conservative daily loss limit
cooldown_seconds: 60 # 60 seconds between trades

# Notifications (REQUIRED for production)
telegram_bot_token: '<token>' # REQUIRED: Set your Telegram bot token
telegram_admin_ids: [123456789] # REQUIRED: Add admin Telegram user IDs

# Data storage
database_url: 'sqlite+aiosqlite:///./prod_bot.sqlite' # Consider PostgreSQL for production
parquet_dir: './prod_data_parquet'

# Execution mode
dry_run: false # Live trading in production

# Live trading configuration
preflight_simulate: true # Enable preflight simulation for live trades
max_retries_send: 3 # Maximum retries for transaction sending

# Signer configuration (choose one method)
keypair_path_enc: './secrets/solana-main.enc' # decrypted in-memory via secret_vault
keypair_path_json: null # alternative JSON keypair path
external_signer_cmd: null # alternative signer command

# Safety settings
allow_devnet: false # Never allow devnet in production
unsafe_allow_high_slippage: false # Never allow high slippage in production
